site_name: cyberpyre
nav:
  - Welcome: index.md
  - Mechanics: mechanics.md
  - Cyberware: cyberware.md
  - Tables: tables.md
  - About: about.md
theme:
  name: material
  favicon: img/vamp-teeth-icon.png
  logo: img/darkpack_logo2.png
  palette:
    scheme: slate
    primary: red
    accent: cyan
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
  - stylesheets/extra.css